name: Build

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Building iso disk image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 40960
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/library/debian:trixie-slim
          options: --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; apt install sudo devscripts equivs build-essential -y
            mk-build-deps -i -t "apt -y" -r
            git config --global --add safe.directory /work
            dpkg-buildpackage --root-command=sudo -b -us -uc -tc
            mkdir -p artifacts_output
            mv ../*.deb artifacts_output/
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifacts_output/*
          compression-level: 9 # maximum compression
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`