name: Build

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    name: Building Proton on Ubuntu 20.04
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          sudo apt update; sudo apt install sudo devscripts equivs build-essential -y
          sudo mk-build-deps -i -t "apt -y" -r
          sudo systemctl start docker
          dpkg-buildpackage --root-command=sudo -b -us -uc -tc
          mkdir -p artifacts_output
          sudo mv ../*.deb artifacts_output/
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifacts_output/*
          compression-level: 9 # maximum compression
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`